-- 20260717120000_user_analytics.sql
-- Per-user acquisition + engagement analytics, and a home for daily reports.
--
--   * users gains signup attribution (country, source, referrer, landing,
--     utm) captured at first login, plus login stats kept fresh by
--     record_login() (called from /api/track on every `login` event).
--   * activity_events gains a country column (from Vercel's geo header).
--   * daily_reports stores each generated report so the email is a
--     convenience, not the system of record.

-- ---------------------------------------------------------------------------
-- users: signup attribution + login stats
-- ---------------------------------------------------------------------------
alter table public.users
  add column if not exists signup_country  text,
  add column if not exists signup_source   text,
  add column if not exists signup_referrer text,
  add column if not exists signup_landing  text,
  add column if not exists signup_utm      jsonb,
  add column if not exists first_login_at  timestamptz,
  add column if not exists last_login_at   timestamptz,
  add column if not exists login_count     int not null default 0;

create index if not exists users_created_idx
  on public.users (created_at desc);

-- ---------------------------------------------------------------------------
-- activity_events: country of the request (ISO 3166-1 alpha-2)
-- ---------------------------------------------------------------------------
alter table public.activity_events
  add column if not exists country text check (country is null or length(country) = 2);

create index if not exists activity_events_created_idx
  on public.activity_events (created_at desc);

-- ---------------------------------------------------------------------------
-- record_login: called by /api/track (service role) on every `login` event.
-- Signup attribution is first-write-wins; last_login_at is always refreshed,
-- so it doubles as "last seen while authenticated". login_count only
-- increments when the previous login is >30 min old, because the client
-- fires SIGNED_IN on session restores too — this makes it a session count.
-- ---------------------------------------------------------------------------
create or replace function public.record_login(
  p_user_id  uuid,
  p_country  text default null,
  p_source   text default null,
  p_referrer text default null,
  p_landing  text default null,
  p_utm      jsonb default null
) returns void
language sql
security definer
set search_path = public
as $$
  update public.users set
    login_count     = login_count + (case when last_login_at is null
                                            or last_login_at < now() - interval '30 minutes'
                                          then 1 else 0 end),
    first_login_at  = coalesce(first_login_at, now()),
    last_login_at   = now(),
    signup_country  = coalesce(signup_country,  nullif(p_country, '')),
    signup_source   = coalesce(signup_source,   nullif(p_source, '')),
    signup_referrer = coalesce(signup_referrer, nullif(p_referrer, '')),
    signup_landing  = coalesce(signup_landing,  nullif(p_landing, '')),
    signup_utm      = coalesce(signup_utm, p_utm)
  where id = p_user_id;
$$;

revoke all on function public.record_login(uuid, text, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.record_login(uuid, text, text, text, text, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- daily_reports: one row per report date, service-role only (like
-- activity_events). data holds the full aggregate blob the email is
-- rendered from.
-- ---------------------------------------------------------------------------
create table if not exists public.daily_reports (
  report_date date primary key,
  data        jsonb not null,
  created_at  timestamptz not null default now()
);

alter table public.daily_reports enable row level security;
revoke all on table public.daily_reports from anon, authenticated;
grant all on table public.daily_reports to service_role;

comment on table public.daily_reports is
  'Daily signup/activity aggregates generated by /api/cron/daily-report.';
